name: Build wheels and publish to PyPI

on:
  release:
    types: [published]

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build wheel
        run: |
          python -m pip install build
          python -m build --wheel --sdist --outdir wheelhouse

      - name: Store wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: wheelhouse/*

  test_unix_wheels:
    needs: build_wheels
    name: Test wheels on ${{ matrix.os }} with ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # to not fail all combinations if just one fail
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.11', '3.12']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/download-artifact@v4
        with:
          name: wheels
          path: wheelhouse

      - name: Get wheel filename
        run: echo "WHEELNAME=$(ls ./wheelhouse/python-fold-*none-any.whl)" >> $GITHUB_ENV

      - name: Install wheel and extras
        run: python -m pip install "${{ env.WHEELNAME }}[all_extras,dev]"

      - name: Run tests
        run: |
          pip install -r requirements.txt
          pip install pytest
          python -m pytest

  upload_wheels:
    name: Upload wheels to PyPI
    runs-on: ubuntu-latest
    needs: [build_wheels,test_unix_wheels]

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels
          path: wheelhouse

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: wheelhouse/